name: Red_Alert
description: A Missing Person App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Default
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # Charts
  charts_flutter: ^0.9.0

  # Local Database
  path:
  provider:
  sqflite: ^1.3.0

  # Notification
  flutter_local_notifications: ^3.0.1+2

  # Firestore Cloud
  firebase_core:
  cloud_firestore:

  # Internationalization
  flutter_i18n:

  # Map
  flutter_map: any
  geolocator: ^6.1.7
  geocoding: ^1.0.5

  # Date Format
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Icon and Nanem Edit
  flutter_launcher_icons: "^0.8.0"
  flutter_launcher_name: "^0.0.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/RedAlertLogo.png"

flutter_launcher_name:
  name: "Red Alert"

flutter:
  uses-material-design: true
  assets: 
    - images/
    - images/tutorials/missing_person/
    - images/tutorials/about/
    - images/tutorials/sync/
    - images/tutorials/map/
    - images/tutorials/charts_data_table/

    - assets/
    - assets/flutter_i18n/

