name: Red_Alert
description: A Missing Person App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  charts_flutter: ^0.9.0
  path:
  provider:
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  flutter_launcher_name: "^0.0.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/RedAlertLogo.png"

flutter_launcher_name:
  name: "Red Alert"

flutter:
  uses-material-design: true
